#ifndef _AVR_MCU_328P_H_
#define _AVR_MCU_328P_H_

#define AVRSYSH_MCU_328P	1
#define AVR_MCU_TYPE		"328p"

#define THREAD_STACK_OFFSET	0x180
#define THREAD_PIPE_BUF_SIZE	64

#define SERIAL_RX_BUF_SIZE	16

#define PC_SIZE_BYTES		2

#define THERMAL_SUPPORT		1

#endif // _AVR_MCU_328P_H_
