#ifndef _AVR_MCU_32U4_H_
#define _AVR_MCU_32U4_H_

#define AVRSYSH_MCU_32U4	1
#define AVR_MCU_TYPE		"32u4"

#define THREAD_STACK_OFFSET	0x180
#define THREAD_PIPE_BUF_SIZE	64

#define SERIAL_RX_BUF_SIZE	16

#define PC_SIZE_BYTES		2

#endif // _AVR_MCU_32U4_H_
